Add option to reuse existing windows
lxqt/lximage-qt pull request #455
Opened 2021-09-06 22:26 UTC by xiota

Borrowed from pcmanfm-qt "Single window mode".  Multiple windows can still be opened with the new window command.

2021-09-07 10:00 UTC, tsujan commented
Nice!

I'll review it later but please change "Reuse existing window" to "Single window mode" (it may need a concise tooltip, telling the user what he should expect). Also, the Window tab may be more appropriate for this option.

2021-09-07 14:52 UTC, xiota commented
I've made the changes you've suggested.

2021-09-07 16:37 UTC, tsujan commented
The code seems good but there're a usability problem.

When the user opens multiple images at once in the single-window mode, only the first image is opened. That was why I wasn't fond of such an option in an image viewer.

Since we don't want to add tabs just for this use case, the only solution that comes to my mind is opening the first image in the current window and the others in separate windows. Also, adding "as far as possible" to the tooltip of the new option seems like a good idea to me.

2021-09-07 16:49 UTC, xiota commented
I'll think about it.  But the point of having a single window mode is that it not open new windows.  Users who want new windows to open can just not check the box, which is unchecked by default.  Users can still explicitly open new windows if they want.

2021-09-07 16:58 UTC, tsujan commented
It's a bug that should be fixed.

2021-09-07 17:12 UTC, xiota commented
What is a bug?

2021-09-07 18:06 UTC, stefonarch commented
I like much a single window mode, it's meaning is clear. 
No idea if just a message could be shown in the case when multiple images are to be opened.

2021-09-07 18:18 UTC, xiota commented
@tsujan  @stefonarch   I noticed that the preferences window has a label for messages.  When  single window mode is clicked/unclicked, it could be used to let the user know what will happen when multiple images are opened.  I think the messages shown there are red and bold, so hard to miss.

When multiple images are opened, they could be shown in the thumbnail dock as a "collection".  Users could create a slideshow limited to just a few images.   I don't know how to make folderview do that though, if it's possible.

2021-09-09 02:56 UTC, tsujan requested changes
Depriving the user of an elementary feature like opening multiple images isn't a good idea. We can't compare lximage-qt with pcmanfm-qt in this regard because the latter has tabs.

There can be two solutions, at least. I mentioned one above but it's more complex than my comment. Actually, it isn't a single-window mode anymore but about reusing existing windows. It can confuse the user too.

The second solution is doing what a single-window video player does: it enqueues files when there is more than one. The app needs to show the first image and also a list dialog that contains the names of all images, so that the user could see the other images by clicking its rows (images may be inside different folders).

2021-09-09 17:46 UTC, xiota commented
Adding this as an *option* does not deprive anyone of anything.  The program will continue to open new windows when the box is not checked.  However, not adding this option or making it open multiple windows, even though it is in *single* window mode, does deprive users of a single-window mode that is true to its name.

One reason for these PRs is to add features I consider essential.  While a couple PRs were not for essential features (hiding the menubar), I do consider a *real* single window mode to be essential.  So I will not agree to changes that involve making it open new windows without explicit user action via the "new window" command.

I have no objection to a queuing method that does *not* open new windows ("a list dialog").  However, I would leave them for a later PR.

2021-09-23 23:36 UTC, closed without merging